name: Build and test
on:
  push:
    branches:
      - main
      - actions
jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install cmake libboost-program-options-dev libgtest-dev
      - name: Build gtest
        run: |
          cd /usr/src/gtest
          sudo mkdir build
          cd build
          sudo cmake ..
          sudo make install
      - name: Build repo
        run: |
          ls
          mkdir build
          cd build
          cmake ..
          make
      - name: Run ctest
        run: |
          cd build
          ctest --extra-verbose --output-on-failure
        env:
          GTEST_COLOR: 1