name: Build and test
on:
  push:
    branches:
      - main
      - actions
jobs:
  build-and-test:
    strategy:
      matrix:
        container-tag: ['16.04', '18.04', '20.04']
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.container-tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Install dependencies
        run: |
          apt update
          apt --yes install cmake libboost-program-options-dev libgtest-dev
      - name: Build gtest
        run: |
          cd /usr/src/gtest
          mkdir build
          cd build
          cmake ..
          make install
      - name: Build repo
        run: |
          ls
          mkdir build
          cd build
          cmake ..
          make
      - name: Run ctest
        run: |
          cd build
          ctest --extra-verbose --output-on-failure
        env:
          GTEST_COLOR: 1