name: Build and test
on:
  push:
    branches:
      - main
      - actions
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ubuntu-tag: '18.04'
            init-tz: false
          - ubuntu-tag: '20.04'
            init-tz: true
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.ubuntu-tag }}
    steps:
      - name: Init timezone
        if: ${{ matrix.init-tz }}
        run: |
          echo 'Etc/UTC' > /etc/timezone
          ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime
      - name: System update
        run: |
          apt update
          apt --yes upgrade
      - name: Install dependencies
        run: |
          apt update
          apt --yes install build-essential cmake libboost-program-options-dev libgtest-dev
      - name: Build gtest
        run: |
          cd /usr/src/gtest
          mkdir build
          cd build
          cmake ..
          make
          make install
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Build repo
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Run ctest
        run: |
          cd build
          ctest --extra-verbose --output-on-failure
        env:
          GTEST_COLOR: 1