name: ctest-actions
on:
  push:
    branches:
      - actions
jobs:
  ctest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo apt install libboost-program-options-dev
          mkdir build
          cd build
          cmake ..
          make
          ctest --extra-verbose --output-on-failure